# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AABHMqAWYuRdIlflwi8gksPnlUMQBiSxAqQAAZFms";
    path = fetchgit {
      url = "https://github.com/hexops/xcode-frameworks";
      rev = "9a45f3ac977fd25dff77e58c6de1870b6808c4a7";
      hash = "sha256-xveFYoQu0BT+ZtEsyca/zdQ/so9jPK56SeX3xmF3iro=";
    };
  }
  {
    name = "N-V-__8AAJl1DwBezhYo_VE6f53mPVm00R-Fk28NPW7P14EQ";
    path = fetchgit {
      url = "https://github.com/emscripten-core/emsdk";
      rev = "3bcf1dcd01f040f370e10fe673a092d9ed79ebb5";
      hash = "sha256-ftUQjgMio8G3aHIux9ZckJFYq1Vdfkv5w3830XO1Ris=";
    };
  }
  {
    name = "N-V-__8AALUbbwDKkSH4nbf3Ml_dTWo9qbELvle5i9eQZMuo";
    path = fetchgit {
      url = "https://github.com/raysan5/raygui";
      rev = "9cdfec460b43a17264af3c181c46f62bf107ac17";
      hash = "sha256-Xhx4hX9S+L3/yF7UIJMv5/v4ftu9I/1JrlzK2XVmYVw=";
    };
  }
  {
    name = "raylib-5.6.0-dev-whq8uL592gQ782dF95oci4S61qrNVYK3MhpUpNwFgZ1J";
    path = fetchgit {
      url = "https://github.com/raysan5/raylib";
      rev = "9f831428e6be0eba8762a154e3e9139d4f071970";
      hash = "sha256-hEcnNcIjVET/ZlxPwpn2AbGZzmO9nDV5PBpu221WWik=";
    };
  }
  {
    name = "raylib_zig-5.6.0-dev-KE8REENOBQC-m5nK7M2b5aKSIubJPbPLUYcRhT7aT3RN";
    path = fetchgit {
      url = "https://github.com/raylib-zig/raylib-zig";
      rev = "cd71c85d571027ac8033357f83b124ee051825b3";
      hash = "sha256-NngsgMGHCvM7vln13Scl5/5zy7/3z4xIRhFsxqqIUiA=";
    };
  }
  {
    name = "zemscripten-0.2.0-dev-sRlDqApRAACspTbAZnuNKWIzfWzSYgYkb2nWAXZ-tqqt";
    path = fetchgit {
      url = "https://github.com/zig-gamedev/zemscripten";
      rev = "3fa4b778852226c7346bdcc3c1486e875a9a6d02";
      hash = "sha256-g/sHkcp+zdJEEAaooCS4joPGSij57RVKoLCcef0aRIE=";
    };
  }
  {
    name = "zemscripten-0.2.0-dev-sRlDqFJSAAB8hgnRt5DDMKP3zLlDtMnUDwYRJVCa5lGY";
    path = fetchgit {
      url = "https://github.com/zig-gamedev/zemscripten";
      rev = "00da03b188220374a57cb34cda6230b8d53737ea";
      hash = "sha256-tbZ5bA2Tz4hxSwO1bqHkGkZZtrSP0S7ezOWzcH7wqpw=";
    };
  }
]
